# Example use of gps to send beam of optical photons

/OpNovice/gun/optSource gps
/gps/verbose 0
/gps/particle opticalphoton
/gps/polarization 0 0 1
/gps/number 10000
/gps/time 0 ns

/gps/ene/type Mono
/gps/energy 3.1 eV

/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0. 0. 20. cm
/gps/pos/radius 1.0 cm

/gps/ang/type focused
/gps/ang/rot1 0.0 1.0 0.0
/gps/ang/rot2 1.0 0.0 0.0
/run/beamOn 1


